Include var.tags in node workers
opendatacube/datacube-k8s-eks pull request #282
Opened 2022-02-04 00:57 UTC by jmettes

**Any PRs will require running `terraform fmt -recursive` successfully first. Please install terraform version > `v0.15` on your local setup for this activity.**

# Why this change is needed
> Describe why this change is needed, what issues it will fix and the benefits the change will add

I want to track costs of infra-dev in Cloudability by tag, and I can see most resources using the `stack_name` tag - except the EC2 worker nodes. Only `var.node_extra_tags` currently get passed, not `var.tags` - like every other resource.

# Negative effects of this change
> Will making this change break or change an existing functionality? flag it here

It shouldn't make any difference other than adding additional generic tags. Unless there was some reason to only include `var.node_extra_tags`, which would otherwise break something if generic `var.tags` were included.

Sample `terraform plan` for infra-dev seems to preserve existing tags - i.e., _"# (9 unchanged blocks hidden)"_ - and includes new tags.

<details>
<summary>Expand terraform plan</summary>

```terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.cognito_user_auth.aws_cognito_user_pool.pool has changed
  ~ resource "aws_cognito_user_pool" "pool" {
        id                        = "ap-southeast-2_TLceJMzTO"
      ~ last_modified_date        = "2022-02-01T00:07:20Z" -> "2022-02-02T02:36:29Z"
        name                      = "infra-dev-eks-user-auth"
        tags                      = {
            "Name"        = "infra-dev-eks-user-auth"
            "branch"      = "NEMO"
            "cost_code"   = ""
            "department"  = "geoscience australia"
            "division"    = "EGD"
            "environment" = "dev"
            "namespace"   = "infra"
            "owner"       = "deacepticons"
            "project"     = "DEA"
            "section"     = "Digital Earth Australia"
            "stack_name"  = "infra-dev-eks"
        }
        # (9 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may
include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_acm_certificate.domain_cert will be read during apply
  # (config refers to values not yet known)
 <= data "aws_acm_certificate" "domain_cert"  {
      ~ arn         = "arn:aws:acm:ap-southeast-2:451924316694:certificate/b5e08874-4245-4ce8-9db4-5bbad43e79ad" -> (known after apply)
      ~ id          = "arn:aws:acm:ap-southeast-2:451924316694:certificate/b5e08874-4245-4ce8-9db4-5bbad43e79ad" -> (known after apply)
      ~ status      = "ISSUED" -> (known after apply)
      ~ tags        = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }

  # module.odc_eks.module.eks.aws_autoscaling_group.nodes will be updated in-place
  ~ resource "aws_autoscaling_group" "nodes" {
        id                        = "eks-lt-0083e4a903d5c7a21-nodes"
        name                      = "eks-lt-0083e4a903d5c7a21-nodes"
        # (22 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-0083e4a903d5c7a21"
            name    = "infra-dev-eks2022012402435993510000000c"
          ~ version = "2" -> (known after apply)
        }

      + tag {
          + key                 = "branch"
          + propagate_at_launch = true
          + value               = "NEMO"
        }
      + tag {
          + key                 = "cost_code"
          + propagate_at_launch = true
        }
      + tag {
          + key                 = "department"
          + propagate_at_launch = true
          + value               = "geoscience australia"
        }
      + tag {
          + key                 = "division"
          + propagate_at_launch = true
          + value               = "EGD"
        }
      + tag {
          + key                 = "project"
          + propagate_at_launch = true
          + value               = "DEA"
        }
      + tag {
          + key                 = "section"
          + propagate_at_launch = true
          + value               = "Digital Earth Australia"
        }
      + tag {
          + key                 = "stack_name"
          + propagate_at_launch = true
          + value               = "infra-dev-eks"
        }
        # (9 unchanged blocks hidden)
    }

  # module.odc_eks.module.eks.aws_autoscaling_group.spot_nodes[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "spot_nodes" {
        id                        = "eks-lt-01b63475212926cf3-spot"
        name                      = "eks-lt-01b63475212926cf3-spot"
        # (22 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-01b63475212926cf3"
            name    = "infra-dev-eks2022012402435993490000000b"
          ~ version = "2" -> (known after apply)
        }

      + tag {
          + key                 = "branch"
          + propagate_at_launch = true
          + value               = "NEMO"
        }
      + tag {
          + key                 = "cost_code"
          + propagate_at_launch = true
        }
      + tag {
          + key                 = "department"
          + propagate_at_launch = true
          + value               = "geoscience australia"
        }
      + tag {
          + key                 = "division"
          + propagate_at_launch = true
          + value               = "EGD"
        }
      + tag {
          + key                 = "project"
          + propagate_at_launch = true
          + value               = "DEA"
        }
      + tag {
          + key                 = "section"
          + propagate_at_launch = true
          + value               = "Digital Earth Australia"
        }
      + tag {
          + key                 = "stack_name"
          + propagate_at_launch = true
          + value               = "infra-dev-eks"
        }
        # (9 unchanged blocks hidden)
    }

  # module.odc_eks.module.eks.aws_launch_template.node will be updated in-place
  ~ resource "aws_launch_template" "node" {
        id                      = "lt-0083e4a903d5c7a21"
      ~ latest_version          = 2 -> (known after apply)
        name                    = "infra-dev-eks2022012402435993510000000c"
        tags                    = {}
      ~ user_data               = "IyEvYmluL2Jh... <snip>" -> "IyEvYmluL2Jhc2gKc2V... <snip"
        # (9 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # module.odc_eks.module.eks.aws_launch_template.spot[0] will be updated in-place
  ~ resource "aws_launch_template" "spot" {
        id                      = "lt-01b63475212926cf3"
      ~ latest_version          = 2 -> (known after apply)
        name                    = "infra-dev-eks2022012402435993490000000b"
        tags                    = {}
      ~ user_data               = "IyEvYmluL2... <snip>" -> "IyEvYmluL2Jhc2gKc2V... <snip>"
```

</details>

2022-02-04 02:02 UTC, pindge approved these changes

2022-02-07 21:33 UTC, woodcockr requested changes
The additional use of var.tags here is inconsistent with its use on all other resources.
On all other resources var.tags is a `merge()` operation can be used to override the default variables if desired.
In this code the operation is `concat()` and a `dynamic` block. It's not clear to me if this will be problematic if the override behaviour is used (I can't tell from the dynamic block documentation what the behaviour is but I suspect it will be an error due to a duplicate tag).

Also worth noting the override behaviour isn't consistent all the way into the odc_eks module since it explicitly accepts the `owner`, `namespace` and `environment` vars in its interface, as well as `tags` but doesn't always `merge()`. It is of course possible to explicitly set these and achieve the same result but it's a little peculiar now I'm looking at it with this PR context.

I think this should be made consistent behaviour were possible, at least support the override semantics so that should `var.tags` be used that way the module won't toss an error.

2022-02-09 11:06 UTC, jmettes commented
Cheers for the suggestion. I've adjusted the workers to use `merge()` instead of the `concat()` to be consistent with the rest of the resources. Also noticed `main.tf` using different capitilisation for key values to the rest of the module.

> Also worth noting the override behaviour isn't consistent all the way into the odc_eks module

Do you mean there are other resources that aren't following the `merge(..., var.tags)` pattern?

---

Since we're talking about about tags, I noticed we're adding this `node_extra_tag` for sandbox and dev:

```
module "odc_eks" {
  ...
  node_extra_tags = {
    "k8s.io/cluster-autoscaler/node-template/label/nodegroup" = "eks"
  }
  ...
```
Is this perhaps something that should just be part of the hard-coded tags (i.e., like the `k8s.io/cluster-autoscaler/node-template/label/nodetype` ones)?

---

I ran a plan against infra-dev again, it looks okay to me.

<details>
<summary>Expand terraform plan</summary>

```terraform
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.cognito_user_auth.aws_cognito_user_pool.pool has changed
  ~ resource "aws_cognito_user_pool" "pool" {
        id                        = "ap-southeast-2_TLceJMzTO"
      ~ last_modified_date        = "2022-02-01T00:07:20Z" -> "2022-02-04T02:40:41Z"
        name                      = "infra-dev-eks-user-auth"
        tags                      = {
            "Name"        = "infra-dev-eks-user-auth"
            "branch"      = "NEMO"
            "cost_code"   = ""
            "department"  = "geoscience australia"
            "division"    = "EGD"
            "environment" = "dev"
            "namespace"   = "infra"
            "owner"       = "deacepticons"
            "project"     = "DEA"
            "section"     = "Digital Earth Australia"
            "stack_name"  = "infra-dev-eks"
        }
        # (9 unchanged attributes hidden)







        # (8 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may
include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_acm_certificate.domain_cert will be read during apply
  # (config refers to values not yet known)
 <= data "aws_acm_certificate" "domain_cert"  {
      ~ arn         = "arn:aws:acm:ap-southeast-2:451924316694:certificate/b5e08874-4245-4ce8-9db4-5bbad43e79ad" -> (known after apply)
      ~ id          = "arn:aws:acm:ap-southeast-2:451924316694:certificate/b5e08874-4245-4ce8-9db4-5bbad43e79ad" -> (known after apply)
      ~ status      = "ISSUED" -> (known after apply)
      ~ tags        = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }

  # module.odc_eks.module.eks.data.aws_ami.eks_worker will be read during apply
  # (config refers to values not yet known)
 <= data "aws_ami" "eks_worker"  {
      ~ architecture          = "x86_64" -> (known after apply)
      ~ arn                   = "arn:aws:ec2:ap-southeast-2::image/ami-00e00ec68f7361f99" -> (known after apply)
      ~ block_device_mappings = [
          - {
              - device_name  = "/dev/xvda"
              - ebs          = {
                  - "delete_on_termination" = "true"
                  - "encrypted"             = "false"
                  - "iops"                  = "0"
                  - "snapshot_id"           = "snap-0069c2a6cf78313c0"
                  - "throughput"            = "0"
                  - "volume_size"           = "20"
                  - "volume_type"           = "gp2"
                }
              - no_device    = ""
              - virtual_name = ""
            },
        ] -> (known after apply)
      ~ creation_date         = "2022-01-23T08:01:32.000Z" -> (known after apply)
      ~ description           = "EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.19.15, docker: 20.10.7-5.amzn2, containerd: 1.4.6-7.amzn2)" -> (known after apply)
      ~ ena_support           = true -> (known after apply)
      ~ hypervisor            = "xen" -> (known after apply)
      ~ id                    = "ami-00e00ec68f7361f99" -> (known after apply)
      ~ image_id              = "ami-00e00ec68f7361f99" -> (known after apply)
      ~ image_location        = "amazon/amazon-eks-node-1.19-v20220123" -> (known after apply)
      ~ image_owner_alias     = "amazon" -> (known after apply)
      ~ image_type            = "machine" -> (known after apply)
      + kernel_id             = (known after apply)
      ~ name                  = "amazon-eks-node-1.19-v20220123" -> (known after apply)
      ~ owner_id              = "602401143452" -> (known after apply)
      + platform              = (known after apply)
      ~ platform_details      = "Linux/UNIX" -> (known after apply)
      ~ product_codes         = [] -> (known after apply)
      ~ public                = true -> (known after apply)
      + ramdisk_id            = (known after apply)
      ~ root_device_name      = "/dev/xvda" -> (known after apply)
      ~ root_device_type      = "ebs" -> (known after apply)
      ~ root_snapshot_id      = "snap-0069c2a6cf78313c0" -> (known after apply)
      ~ sriov_net_support     = "simple" -> (known after apply)
      ~ state                 = "available" -> (known after apply)
      ~ state_reason          = {
          - "code"    = "UNSET"
          - "message" = "UNSET"
        } -> (known after apply)
      ~ tags                  = {} -> (known after apply)
      ~ usage_operation       = "RunInstances" -> (known after apply)
      ~ virtualization_type   = "hvm" -> (known after apply)
        # (2 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.odc_eks.module.eks.aws_autoscaling_group.nodes will be updated in-place
  ~ resource "aws_autoscaling_group" "nodes" {
        id                        = "eks-lt-0083e4a903d5c7a21-nodes"
        name                      = "eks-lt-0083e4a903d5c7a21-nodes"
        # (22 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-0083e4a903d5c7a21"
            name    = "infra-dev-eks2022012402435993510000000c"
          ~ version = "2" -> (known after apply)
        }

      + tag {
          + key                 = "branch"
          + propagate_at_launch = true
          + value               = "NEMO"
        }
      + tag {
          + key                 = "cost_code"
          + propagate_at_launch = true
        }
      + tag {
          + key                 = "department"
          + propagate_at_launch = true
          + value               = "geoscience australia"
        }
      + tag {
          + key                 = "division"
          + propagate_at_launch = true
          + value               = "EGD"
        }
      + tag {
          + key                 = "project"
          + propagate_at_launch = true
          + value               = "DEA"
        }
      + tag {
          + key                 = "section"
          + propagate_at_launch = true
          + value               = "Digital Earth Australia"
        }
      + tag {
          + key                 = "stack_name"
          + propagate_at_launch = true
          + value               = "infra-dev-eks"
        }
        # (9 unchanged blocks hidden)
    }

  # module.odc_eks.module.eks.aws_autoscaling_group.spot_nodes[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "spot_nodes" {
        id                        = "eks-lt-01b63475212926cf3-spot"
        name      [...]

2022-02-09 22:58 UTC, woodcockr approved these changes

2022-02-09 23:01 UTC, woodcockr commented
That's more consistent @jmettes. Thanks for tweaks.

> > Also worth noting the override behaviour isn't consistent all the way into the odc_eks module
> 
> Do you mean there are other resources that aren't following the `merge(..., var.tags)` pattern?

I meant that most of the modules are simply apply var.tags and accepting it as an input, but some others split them out as var.environment, var.owner, ... They are eventually merged with var.tags so no harm done, it's just a little inconsistent. To some extent its because the odc_eks module uses these in it's naming convention for resources so these tags need to be supplied to support the unique resource naming.

2022-02-16 03:45 UTC, merged